### PR TITLE
Update conduct@ and cocc@

### PR DESCRIPTION
**Pull request by revi**
So that all mails go to mailing list.

### CODE REVIEW

**Comment by MacFan4000** [comment]
@revi this would mean that you can remove your alias?

**Comment by MacFan4000** [comment]
@revi , also I see you updated the ACL project on phab, but not the other project

**Comment by MacFan4000** [comment]
@revi https://phabricator.miraheze.org/project/view/34/

**Comment by MacFan4000** [comment]
Though I guess only phab admins can do anything with it. (Commenting here as I dont have IRC access at the moment)

**Comment by revi** [comment]
For the completeness

1. I will do it once I clear it from my various email point
2. that project does not matter when it comes to ACL purpose: that project can be joined by anyone. As far as I know, the project to control the ACL to the tasks in the space is the one I modified.

**Comment by MacFan4000** [comment]
> 2. that project does not matter when it comes to ACL purpose: that project can be joined by anyone. As far as I know, the project to control the ACL to the tasks in the space is the one I modified.
It cant be joined by anyone. The edit and join policya are restricted to phab admins (just saying)

**Comment by revi** [comment]
Uh conductwiki. I forgot about that but void dealt with that. so Thanks void!

**Pull request merged**
