### PR TITLE
create www cert for wikiletras.tk

### PR DESCRIPTION
**Pull request by Reception123**
user wants the redirect to be from wikiletras.tk to www.wikiletras.tk

### CODE REVIEW

**Comment by JohnFLewis** [comment]
You're adding a certificate but not using it + redirecting from a registered custom domain to one that now no longer exists in ssl.yaml

**Comment by Reception123** [comment]
User just needs the www, there's no need for the redirect then.

**Comment by Reception123** [comment]
I'd rather ask the user to make sure, though

**Comment by Reception123** [comment]
"I need www.wikiletras.tk only. Thanks. DoerNoc (talk) 20:08, 18 April 2017 (UTC)"

**Pull request merged**
