### PR TITLE
switch branch to REL1_29

### PR DESCRIPTION
**Pull request by Reception123**
[DO NOT merge unless you are upgrading]

### CODE REVIEW

**Comment by JohnFLewis** [comment]
This is not the way it will be done.

This way will result in downtime. You want a phased method. Upgrade a depooled server, swap depools then repool.

**Comment by Reception123** [comment]
Oh, I thought that, but wasn't sure if that was needed with test1. Well then closing this since @NDKilla can take care of the commits.

**Comment by JohnFLewis** [comment]
Though this is fine if puppet is DISABLED before this is merged.

**Comment by Reception123** [comment]
<JohnLewis> Reopen it. Disabling is less ugly

**Pull request merged**
