### PR TITLE
Update default.vcl

### PR DESCRIPTION
**Pull request by joaquinito01**

### CODE REVIEW

**Comment by paladox** [comment]
I'm not sure if this is a test edit?

**Comment by joaquinito01** [comment]
No, is not a test edit, merge it now.

**Comment by RhinosF1** [comment]
> No, is not a test edit, merge it now.

Our operations team have to ensure all changes will work before deploying them, please ensure you remain polite as they are only trying to act in Miraheze’s interests. Contributing on this repo is covered by https://meta.miraheze.org/wiki/Code_of_Conduct

**Comment by joaquinito01** [comment]
@RhinosF1 When is deployed???

**Comment by RhinosF1** [comment]
It deploys 10-15 mins after being merged

**Comment by RhinosF1** [comment]
Believed to be incorrect and created by cross platform abuser

**Comment by paladox** [comment]
Not correct and sock puppet confirmed.

**Pull request closed without merging**
