### PR TITLE
automatically update Miraheze extensions

### PR DESCRIPTION
**Pull request by Reception123**
As you know, I am not too good with these things, so please double check and tell me what is wrong and what needs to be changed.

### CODE REVIEW

**Comment by JohnFLewis** [comment]
1) There’s no auth involved here so GH will reject push attempts.
2) This is trying to automate something for no reason.
3) It’s messy.
4) I have several times made commits to extensions and told people “Don’t deploy this until x is done” or maybe I’m doing a large amount of work on an (ManageWiki+CreateWiki in the past) which requires things like Scheme changes. This doesn’t take that into account so would automatically deploy broken code.

It’s risk for no reward.

**Comment by Reception123** [comment]
This PR also includes changing @MirahezeSSLBot to MirahezeGitHubBot since it will now have multiple purposes

**Comment by Reception123** [comment]
ok

**Comment by Reception123** [comment]
@JohnFLewis Is there a change now that can't be deployed (so I know if I can go ahead with the manual update)?

**Pull request closed without merging**
