### PR TITLE
CSP: add iwiki.eu.org mirrors

### PR DESCRIPTION
**Pull request by RhinosF1**

### CODE REVIEW

**Review by Universal-Omega — CHANGES_REQUESTED** [review]
Merge conflict needs resolved now.

**Comment by Universal-Omega** [comment]
@RhinosF1 - merge conflict still needs resolved.

**Comment by The-Voidwalker** [comment]
For T7161. Will review tomorrow and make sure these are good to add. @Reception123 @Southparkfan any comments regarding this site?

**Comment by JohnFLewis** [comment]
@The-Voidwalker is handling the CSP policy implementation. Assigning this to him to ensure it has a responsible person attached.

**Comment by Universal-Omega** [comment]
This will probably need redone since csp_whitelist no longer exists and has been replaced by csp.yaml.

**Pull request closed without merging**
