### PR TITLE
install HTMLDoc for PdfBook

### PR DESCRIPTION
**Pull request by Reception123**
There's probably some mistakes so needs review first.
@JohnFLewis

### CODE REVIEW

**Comment by JohnFLewis** [comment]
The name is bad (it's but maps) and why are you curling an entire git repo (won't work) and then why are you not using that git repo but instead using apt? Isn't package {} not enough?

**Comment by Reception123** [comment]
@JohnFLewis Hmm, not sure what I should do instead. Is cloning the repo as a submodule a better idea?

**Comment by JohnFLewis** [comment]
I don't know what you're trying to achieve. Looking at what you're trying to do above, yes a submodule

**Comment by Reception123** [comment]
Ok, I'll do that. It's for https://www.mediawiki.org/wiki/Extension:PdfBook#Installation

**Comment by Reception123** [comment]
@JohnFLewis HTMLDoc is not php so will a require_once work, or should it be cloned directly into the PdfBook repo?

**Comment by JohnFLewis** [comment]
I've just looked at the link above and it mentions nothing about source code unless compiling. Which brings me back to my earlier question, why not just use package {}?

**Comment by Reception123** [comment]
Changed. @NDKilla's PR load is back to 5 again ;)

**Pull request merged**
