### PR TITLE
mediawiki-varnish: block some IPs

### PR DESCRIPTION
**Pull request by RhinosF1**
Rough idea as I'm mobile, please check syntax & format

### CODE REVIEW

**Comment by RhinosF1** [comment]
Idea stole from https://www.tothenew.com/blog/allowreject-ip-at-varnish-level/

**Comment by Southparkfan** [comment]
You're using Varnish syntax inside an NGINX config file? That's not going to work.

**Comment by RhinosF1** [comment]
The folder said Varnish! I guess not.

Any idea how to make this work?

**Comment by Southparkfan** [comment]
At the beginning of every location / { } block:
deny "45.145.65.154";
deny "13.75.225.45";
deny "2607:f1c0:83f:b100::54:d55";
deny "216.250.65.144";
deny "45.145.65.144";

**Pull request merged**
