### PR TITLE
Add .DS_Store to .gitignore

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by revi** [comment]
+1 but... shouldn't everybody also put this on their own `.gitignore`?

**Comment by paladox** [comment]
Oh you can have your own .gitignore? I did not know that :).

How would I create my own .gitignore please?

**Comment by revi** [comment]
[gitignore](https://git-scm.com/docs/gitignore)

$home/.gitignore should work.

**Comment by paladox** [comment]
Thanks :)

**Pull request merged**
