### PR TITLE
motd: Puppet 4 support

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by Reception123** [comment]
@paladox are you sure this doesn't break anything for the current puppet version?

**Comment by paladox** [comment]
@Reception123 just looked and stdlib includes validate_numeric which means it has to support puppet 3+.

**Comment by paladox** [comment]
https://www.google.co.uk/search?client=safari&channel=ipad_bm&dcr=0&source=hp&ei=eQl2Wp7EN8jzUq7yldgB&q=puppet+3+validate_numeric&oq=puppet+3+validate_numeric&gs_l=psy-ab.3..35i39k1j0l9.474.2392.0.2501.12.10.0.0.0.0.105.676.7j2.9.0....0...1c.1j2.64.psy-ab..3.9.676.0..0i131k1.0.sSHyYvjTgAI

**Comment by JohnFLewis** [comment]
@Reception123 this can be merged

**Pull request merged**
