### PR TITLE
Rename shell user

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by clarfonthey** [comment]
Looks fine to me, assuming Puppet will actually handle renaming the users correctly.

This can be done later, but would it be possible to make the monitoring users draw from the user data in the Puppet config, so that you don't have to worry about emails etc. being in sync?

**Comment by RhinosF1** [comment]
@clarfonthey: Puppet will not handle renaming users. It will have to be done manually.

**Comment by RhinosF1** [comment]
> This can be done later, but would it be possible to make the monitoring users draw from the user data in the Puppet config, so that you don't have to worry about emails etc. being in sync?

if someone patches to user or monitoring module to work with that.

**Comment by Universal-Omega** [comment]
> @clarfonthey: Puppet will not handle renaming users. It will have to be done manually.

Yeah that's why I didn't merge yet I'll handle rename manually later then merge this.

**Pull request closed without merging**
