### PR TITLE
automate copying private keys for SSL certs (T7582)

### PR DESCRIPTION
**Pull request by Reception123**

### CODE REVIEW

**Review by Universal-Omega — APPROVED** [review]

**Comment by JohnFLewis** [comment]
You shouldn’t be using the master source repo to push changes and stage commits

**Comment by Reception123** [comment]
> You shouldn’t be using the master source repo to push changes and stage commits

Should I be using /home/puppet-users/ssl-keys then? Or is there another repo? (I've always used the puppet-users dir out of habit so I wouldn't know)

**Comment by JohnFLewis** [comment]
The puppet-users one is the only copy I know of currently, unless someone has cloned it elsewhere as well

**Comment by Reception123** [comment]
That's fine then, I actually thought if I did that someone would say I should do it directly, but I guess it's the opposite :P

**Pull request merged**
