### PR TITLE
Add preload to HSTS

### PR DESCRIPTION
**Pull request by revi**
Not sure if this will affect the custom domain, but submitting anyway. Please correct me if wrong.

Thanks for review anyway, Referenced commit d9adcf4042ac256c191ea5b4c1f77607a6bd41e0.

### CODE REVIEW

**Comment by revi** [comment]
Ping @Southparkfan.

**Comment by revi** [comment]
ping @Southparkfan

**Comment by Southparkfan** [comment]
I have already discussed (along with asking questions) this a lot of times in the past and recently, but not on GitHub (and not with you actually) so I'll paste my comment here (and hopefully finally have a response from soneone).

Do we realize that if we merge this, there is no way back? If we deem it necessary to disable HSTS (which is partially possible, by setting max-age=1 and hoping most visitors will visit the wikis in the period between when we set max-age=1 and when we disable HTTPS/introduce self-signed HTTPS), that is not possible anymore. **Miraheze will always need to present a valid wildcard certificate, forever.**

**Comment by Southparkfan** [comment]
@JohnFLewis says it's OK.

Will merge when the db crisis is over.

**Comment by Southparkfan** [comment]
Ok, I totally forgot about this, but I think it's better to merge this when I have time to merge & deploy at the same moment.

Scheduled for tomorrow.

**Pull request merged**
