### PR TITLE
CSP: Replace *.freenode.net with *.libera.chat

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Review by dmehus — APPROVED** [review]
@paladox: ^

**Comment by JohnFLewis** [comment]
Has this been communicated to communities that still use the freenodeChat client on Miraheze? As this is a breaking change for those.

**Comment by Universal-Omega** [comment]
> Has this been communicated to communities that still use the freenodeChat client on Miraheze? As this is a breaking change for those.

There aren't any anymore as all wikis using it where replaced with Libera. I would like to also note Freenode has become a privacy risk and only removed *.freenode.net per what @dmehus said in #1764 and as he is trust and safety. I recognize this can be considered yet another change by SRE not discussed with the community, but this in particular was necessary, and not solely the decision of SRE against the global wishes of the community, but necessary to maintain the privacy within Miraheze.

I am not against a specific wiki site notice being added about the change however, if it is felt as being necessary.

**Comment by JohnFLewis** [comment]
And that decision by Doug was within remit of T&S, has gone through the appropriate processes and consequently is a decision taken on behalf of T&S to not engage the community on this matter? If so, I am even more concerned that the community are being ignored and taken out of decision making for a *community-centric* project

**Comment by dmehus** [comment]
> And that decision by Doug was within remit of T&S, has gone through the appropriate processes and consequently is a decision taken on behalf of T&S to not engage the community on this matter? If so, I am even more concerned that the community are being ignored and taken out of decision making for a _community-centric_ project

**Correction:** It was _not_ done within my Trust and Safety capacity. I strongly recommended the change in a community capacity, and it was not a _decision_ either, but rather a strong _recommendation_.

**Comment by JohnFLewis** [comment]
Okay, so T&S have no involvement here, so it was an SRE decision to proceed with no community engagement.

**Pull request merged**
