### PR TITLE
Whitelist *.archive.org

### PR DESCRIPTION
**Pull request by MusikAnimal**
This is used by the YouTube extension following https://github.com/miraheze/YouTube/pull/11

### CODE REVIEW

**Comment by dmehus** [comment]
@MusikAnimal I suggested this be whitelisted awhile back and perhaps I didn't push strong enough, but your argument there I think is even stronger. :+1: from me.

**Comment by MusikAnimal** [comment]
Is the concern about privacy? I would guess not considering we've whitelisted Google, YouTube, Facebook, Twitter, etc.

**Review by ugochimobi — APPROVED** [review]

**Review by Universal-Omega — APPROVED** [review]
Even though I did not want to have it done last time I do think the reason given this is reason enough to at least consider it under our new policy for CSP whitelisting.

**Comment by R4356th** [comment]
Just noting that this was declined earlier due to very good reasons- https://phabricator.miraheze.org/T6771.

**Comment by Reception123** [comment]
A new CSP policy is being worked on and this will be reviewed and approved/declined subject to the upcoming policy.

**Comment by Universal-Omega** [comment]
> Just noting that this was declined earlier due to very good reasons- https://phabricator.miraheze.org/T6771.

Yes I agree, but I also agree that there are other good points regarding Google and Dropbox. If this is declined I hope we can review those as well and see if they are absolutely needed or if we can change that.

**Comment by Universal-Omega** [comment]
Also, merge conflict needs resolved.

**Comment by JohnFLewis** [comment]
@The-Voidwalker is handling the CSP policy implementation. Assigning this to him to ensure it has a responsible person attached.

**Comment by Universal-Omega** [comment]
This will probably need redone since csp_whitelist no longer exists and has been replaced by csp.yaml.

**Comment by Reception123** [comment]
Will have to close due to the unresovable conflict because of the change in the CSP system.

**Pull request closed without merging**
