### PR TITLE
Add Flickr and Pixabay to CSP whitelist

### PR DESCRIPTION
**Pull request by dmehus**
Common sense addition of the world's largest photo sharing repository, or, at the very least, CreativeCommons-licensed photo sharing repository for use with external images. Likewise, Pixabay is a very large repository of royalty free images licensed under a Pixabay License requiring attribution only.

### CODE REVIEW

**Comment by Reception123** [comment]
I have no objections per the reasons given. @dmehus could you please change the default description that just says "update X" with a short description?

**Comment by dmehus** [comment]
> I have no objections per the reasons given. @dmehus could you please change the default description that just says "update X" with a short description?

Sure. On the PR, or the commit, or both?

**Comment by Reception123** [comment]
> > I have no objections per the reasons given. @dmehus could you please change the default description that just says "update X" with a short description?
> 
> Sure. On the PR, or the commit, or both?

Just the PR title is fine

**Comment by dmehus** [comment]
> > > I have no objections per the reasons given. @dmehus could you please change the default description that just says "update X" with a short description?
> > 
> > 
> > Sure. On the PR, or the commit, or both?
> 
> Just the PR title is fine

Alright.

**Pull request merged**
