### PR TITLE
Only allow system administrators to use logbot

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
There is no need to restrict the log bot. There has been no problem in 6 years, I don’t understand people’s obsessions with this?

**Comment by Reception123** [comment]
My ultimate view based on the points expressed above is that unless there's a major troll issue, there's not a real need to do this and the current system has worked fine.

**Comment by JohnFLewis** [comment]
This has been discussed numerous times, and I know for a fact you have been involved in at least one of these discussions.

**Comment by Universal-Omega** [comment]
> This has been discussed numerous times, and I know for a fact you have been involved in at least one of these discussions.

Then I'm sorry but I don't recall. But truly I do value your advice and I'm truly sorry you thought just because you left I did this.

**Pull request closed without merging**
