### PR TITLE
base::puppet: remove temporary Buster; use Bullseye

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by RhinosF1** [comment]
Is this now supported?

**Comment by Universal-Omega** [comment]
> Is this now supported?

Should be.

**Review by RhinosF1 — APPROVED** [review]
http://apt.puppetlabs.com/pool/bullseye/puppet7/p/

**Comment by Universal-Omega** [comment]
Per IRC:
> 10:23 AM <+ CosmicAlpha> RhinosF1: http://apt.puppetlabs.com/pool/bullseye/puppet7/p/ — https://github.com/miraheze/puppet/pull/2188 says it didn't support for server or DB is why, but that seems to indicate it now does I think.

**Comment by JohnFLewis** [comment]
It’s annoying support was added literally days after migration, but at least support exists now.

**Pull request merged**
