### PR TITLE
Use testing branch for mw-config for testing

### PR DESCRIPTION
**Pull request by MacFan4000**

### CODE REVIEW

**Comment by paladox** [comment]
https://github.com/miraheze/puppet/blob/master/modules/mediawiki/manifests/init.pp#L46

**Comment by MacFan4000** [comment]
How would it be done then?

**Comment by paladox** [comment]
You would need to add a new var to https://github.com/miraheze/puppet/blob/master/modules/mediawiki/manifests/init.pp#L3 named differentily otherwise it will conflict then do mediawiki::<new var>: <branch>

**Comment by MacFan4000** [comment]
Mediawiki has that as well

**Comment by MacFan4000** [comment]
Now I have created a REL1_31 branch on mw-config

**Pull request closed without merging**
