### PR TITLE
mwdeploy: fix tests

### PR DESCRIPTION
**Pull request by Universal-Omega**
## Summary by CodeRabbit

- **New Features**
	- Enhanced the `check_up` function to support optional client certificate usage for HTTPS requests.
- **Bug Fixes**
	- Updated test cases to reflect changes in certificate verification handling, ensuring accurate testing in various environments.

### CODE REVIEW

**Comment by redbluegreenhat** [comment]
I don't get this code at all, a function is being declared inside another function? RhinosF1's review will be more helpful than whatever feedback I can offer.

**Comment by Universal-Omega** [comment]
> I don't get this code at all, a function is being declared inside another function? RhinosF1's review will be more helpful than whatever feedback I can offer.

Yes, a function inside a function seemed cleaner to call the function rather than trying to hack around cert directly where it makes a request, it seemed easier to read to just add a make_request method, but rather than a seperate method, I put it inside the check_up method so it contains its scope since we don't need it anywhere else.

**Comment by RhinosF1** [comment]
This seems to be failing CI with type errors

**Comment by RhinosF1** [comment]
@coderabbitai review

**Comment by RhinosF1** [comment]
What was the original CI error we are trying to solve with this?

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Not awful but feel free to drop the type hints if you can't get them to work.

**Pull request merged**
