### PR TITLE
mediawiki: Update composer to version 2

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Isn't this done with #1892?

**Comment by paladox** [comment]
> Isn't this done with #1892?

Kind of, I think I'm going to do things differently. Buster uses version 1.8 though bullseye uses 2.0.

**Comment by paladox** [comment]
Though I guess I can just repurpose his change so he gets some credit.

**Comment by paladox** [comment]
#1892 1892

**Pull request closed without merging**
