### PR TITLE
change wiki.valentinaproject.org to LE

### PR DESCRIPTION
**Pull request by Reception123**
per request. Site is down. Please merge this ASAP. @miraheze/operations

### CODE REVIEW

**Comment by JohnFLewis** [comment]
What would have helped this get merged earlier is using the -r param. As the way this was done requires the key to be changed which massively delays the process (and based on the past, can lead up to a week delay).

**Comment by Reception123** [comment]
-r? The cert was originally StartSSL

**Comment by JohnFLewis** [comment]
-r generates a LE cert using the CSR without changing the private key or the CSR.

**Comment by Reception123** [comment]
Ok. Didn't know. Will do that in the future

**Pull request merged**
