### PR TITLE
Customize Phab Logo/Wordmark

### PR DESCRIPTION
**Pull request by MacFan4000**
Logo is 80x80px version of Miraheze logo, wordmark/text reads Miraheze. File is here. https://phabricator.miraheze.org/F745359

### CODE REVIEW

**Comment by JohnFLewis** [comment]
I like the contrasting dark blue/white scheme with phab. I feel like yellow would ruin such a nice design and probably stand out too much

**Comment by MacFan4000** [comment]
Its now a white version of the logo.

**Comment by MacFan4000** [comment]
@JohnFLewis I have now changed the logo color to match the phab color scheme as much as possible.

**Comment by MacFan4000** [comment]
15:14 <MacFan4000> That’s how phab would look if my puppet pr was merged https://usercontent.irccloud-cdn.com/file/xnU4qOXz/IMG_0056.PNG

**Comment by Reception123** [comment]
LGTM.
@revi @NDKilla ?

**Comment by MacFan4000** [comment]
@revi @NDKilla @JohnFLewis @Southparkfan opinions?

**Comment by JohnFLewis** [comment]
Mines above, you addressed my issue and I didn't raise new ones.

**Comment by JohnFLewis** [comment]
BOLD

**Pull request merged**
