### PR TITLE
Add Reddit and Dropbox to CSP whitelist T5685

### PR DESCRIPTION
**Pull request by Amanda-Catherine**

### CODE REVIEW

**Comment by Amanda-Catherine** [comment]
@Southparkfan review requested/needed

**Comment by Southparkfan** [comment]
Fine with me

**Comment by Amanda-Catherine** [comment]
I just copied and pasted what was given on the Phab task.

**Comment by RhinosF1** [comment]
I guess we should ask then

**Comment by Elaeagnifolia** [comment]
Re 59&59: As a Reddit user, I would recommend keeping these lines, as the easily retrievable/exposed URLs for uploaded Reddit videos and images use v.redd.it and i.redd.it respectively. I'm actually not sure, outside of rendering post image thumbnails, if Reddit utilizes redditmedia for serving normal videos/images (at least not visibly). Even if they still do, there's isn't an intuitive process in place to figuring out what the redditmedia URL would be.

See this image as an example:
https://b.thumbs.redditmedia.com/_OjMi-urwiRaIDc6hJ79Lk0ChrdCGLggUCVEXyEGo1o.jpg
https://i.redd.it/ksn1lcio0u051.jpg

**Comment by RhinosF1** [comment]
That makes sense, if it's in use as an active url, makes sense as it's not just forwarding.

**Comment by Southparkfan** [comment]
Just wanted to say I have no objections.

**Comment by Reception123** [comment]
Per SPF this is good to go

**Comment by paladox** [comment]
well *.x.org would only be like test.x.org it won't be test.test.x.org.

**Comment by Reception123** [comment]
@paladox so is there anything we can do about that?

**Comment by paladox** [comment]
@Southparkfan says it's fine, merging.

**Pull request merged**
