### PR TITLE
make requestwiki AI job memory 1750M

### PR DESCRIPTION
**Pull request by Reception123**

### CODE REVIEW

**Comment by dmehus** [comment]
@Reception123 Oops, I meant to click "comment" instead of "approve." Should we test this first before merging, by using the `--parameter` that specifies a minimum memory requirement (like @JohnFLewis did before once or twice)?

**Comment by Reception123** [comment]
> @Reception123 Oops, I meant to click "comment" instead of "approve." Should we test this first before merging, by using the `--parameter` that specifies a minimum memory requirement (like @JohnFLewis did before once or twice)?

The issue is I don't know how to do that because when a wiki status changes the job is triggered but goes directly to the jobrunner which makes it fail, so I can't try running it with the higher memory

**Comment by JohnFLewis** [comment]
> > @Reception123 Oops, I meant to click "comment" instead of "approve." Should we test this first before merging, by using the `--parameter` that specifies a minimum memory requirement (like @JohnFLewis did before once or twice)?
> 
> The issue is I don't know how to do that because when a wiki status changes the job is triggered but goes directly to the jobrunner which makes it fail, so I can't try running it with the higher memory

Disabled jobrunner on jobrunner3

**Comment by Reception123** [comment]
> > > @Reception123 Oops, I meant to click "comment" instead of "approve." Should we test this first before merging, by using the `--parameter` that specifies a minimum memory requirement (like @JohnFLewis did before once or twice)?
> > 
> > 
> > The issue is I don't know how to do that because when a wiki status changes the job is triggered but goes directly to the jobrunner which makes it fail, so I can't try running it with the higher memory
> 
> Disabled jobrunner on jobrunner3

Ah good point since the other mw servers also run jobs now.

**Comment by Reception123** [comment]
It seems to work!

**Pull request merged**
